// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/uni-school/api-gateaway/pkg/core/auth/controller"
	"github.com/uni-school/api-gateaway/pkg/core/auth/service"
	"github.com/uni-school/api-gateaway/pkg/core/user/controller"
	"github.com/uni-school/api-gateaway/pkg/core/user/resource"
	"github.com/uni-school/api-gateaway/pkg/core/user/service"
)

// Injectors from wire.go:

func AuthController() *controller_auth.AuthController {
	iUserResource := resource_user.InitUserResource()
	iAuthService := service_auth.InitAuthService(iUserResource)
	authController := controller_auth.InitAuthController(iAuthService)
	return authController
}

func UserController() *controller_user.UserController {
	iUserResource := resource_user.InitUserResource()
	iUserService := service_user.InitUserService(iUserResource)
	userController := controller_user.InitUserController(iUserService)
	return userController
}
