// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user_microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateUser
type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetUserByEmail
type GetUserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailRequest) Reset()         { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()    {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *GetUserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailRequest.Unmarshal(m, b)
}
func (m *GetUserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailRequest.Merge(m, src)
}
func (m *GetUserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailRequest.Size(m)
}
func (m *GetUserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailRequest proto.InternalMessageInfo

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	Message              string                      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *GetUserByEmailResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUserByEmailResponse) Reset()         { *m = GetUserByEmailResponse{} }
func (m *GetUserByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponse) ProtoMessage()    {}
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *GetUserByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponse.Unmarshal(m, b)
}
func (m *GetUserByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponse.Merge(m, src)
}
func (m *GetUserByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponse.Size(m)
}
func (m *GetUserByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponse proto.InternalMessageInfo

func (m *GetUserByEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserByEmailResponse) GetData() *GetUserByEmailResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserByEmailResponseData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailResponseData) Reset()         { *m = GetUserByEmailResponseData{} }
func (m *GetUserByEmailResponseData) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponseData) ProtoMessage()    {}
func (*GetUserByEmailResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *GetUserByEmailResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponseData.Unmarshal(m, b)
}
func (m *GetUserByEmailResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponseData.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponseData.Merge(m, src)
}
func (m *GetUserByEmailResponseData) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponseData.Size(m)
}
func (m *GetUserByEmailResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponseData proto.InternalMessageInfo

func (m *GetUserByEmailResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user_microservice.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user_microservice.CreateUserResponse")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "user_microservice.GetUserByEmailRequest")
	proto.RegisterType((*GetUserByEmailResponse)(nil), "user_microservice.GetUserByEmailResponse")
	proto.RegisterType((*GetUserByEmailResponseData)(nil), "user_microservice.GetUserByEmailResponseData")
}

func init() {
	proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74)
}

var fileDescriptor_ed89022014131a74 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0x4b, 0x81, 0x8f, 0x21, 0xe1, 0x0b, 0x13, 0x35, 0x1b, 0x12, 0xa2, 0x69, 0x34, 0xc1,
	0x03, 0x25, 0xc1, 0xa3, 0x27, 0x50, 0xe3, 0x1d, 0xe3, 0x41, 0x2f, 0x64, 0x65, 0x27, 0xa6, 0x09,
	0x65, 0xeb, 0xee, 0x56, 0xe3, 0xff, 0xf3, 0xee, 0x5f, 0x32, 0xbb, 0x6d, 0x01, 0x05, 0x02, 0x97,
	0x66, 0x66, 0xde, 0xec, 0xbc, 0x99, 0x37, 0x53, 0xf8, 0x9f, 0x69, 0x52, 0x03, 0xfb, 0x89, 0x52,
	0x25, 0x8d, 0xc4, 0xb6, 0xb5, 0xa7, 0x49, 0x3c, 0x53, 0x52, 0x93, 0x7a, 0x8f, 0x67, 0x14, 0x26,
	0xd0, 0xbe, 0x51, 0xc4, 0x0d, 0x3d, 0x6a, 0x52, 0x13, 0x7a, 0xcb, 0x48, 0x1b, 0x44, 0x08, 0x16,
	0x3c, 0x21, 0xe6, 0x9d, 0x79, 0xbd, 0xc6, 0xc4, 0xd9, 0x78, 0x04, 0x55, 0x4a, 0x78, 0x3c, 0x67,
	0xbe, 0x0b, 0xe6, 0x0e, 0x76, 0xe0, 0x5f, 0xca, 0xb5, 0xfe, 0x90, 0x4a, 0xb0, 0x8a, 0x03, 0x96,
	0xbe, 0xad, 0xa2, 0xe4, 0x9c, 0x58, 0x90, 0x57, 0xb1, 0x76, 0x18, 0x01, 0xae, 0xd3, 0xe9, 0x54,
	0x2e, 0x34, 0x21, 0x83, 0x7a, 0x42, 0x5a, 0xf3, 0xd7, 0x92, 0xb2, 0x74, 0xc3, 0x3e, 0x1c, 0xdf,
	0x93, 0xb1, 0xc9, 0xe3, 0xcf, 0x3b, 0xcb, 0x58, 0xb6, 0xb8, 0x6c, 0xc7, 0x5b, 0x6b, 0x27, 0xcc,
	0xe0, 0xe4, 0x6f, 0xfa, 0x3e, 0x0a, 0x1c, 0x41, 0x20, 0xb8, 0xe1, 0x6e, 0xae, 0xe6, 0xb0, 0x1f,
	0x6d, 0x68, 0x14, 0x6d, 0x2f, 0x79, 0xcb, 0x0d, 0x9f, 0xb8, 0xa7, 0xe1, 0x97, 0x07, 0x9d, 0xdd,
	0x49, 0xd8, 0x02, 0x3f, 0x16, 0x05, 0xad, 0x1f, 0x8b, 0xa5, 0xbc, 0xfe, 0x36, 0x79, 0x2b, 0xbb,
	0xe4, 0x0d, 0x76, 0xc8, 0x5b, 0x5d, 0xc9, 0x8b, 0x5d, 0x80, 0x99, 0x93, 0x57, 0x4c, 0xb9, 0x61,
	0x35, 0x87, 0x34, 0x8a, 0xc8, 0xc8, 0x58, 0x38, 0x4b, 0x45, 0x09, 0xd7, 0x73, 0xb8, 0x88, 0x8c,
	0xcc, 0xf0, 0xdb, 0x83, 0xa6, 0x9d, 0xe1, 0x21, 0x9f, 0x1b, 0x9f, 0x00, 0x56, 0xcb, 0xc2, 0xf3,
	0x2d, 0xca, 0x6c, 0x9c, 0x4e, 0xe7, 0x62, 0x4f, 0x56, 0xb1, 0x0e, 0x82, 0xd6, 0x6f, 0xc1, 0xb0,
	0x77, 0x80, 0xf0, 0x39, 0xc5, 0xe5, 0xc1, 0x2b, 0x1a, 0x9f, 0x3e, 0x77, 0x07, 0xee, 0xf4, 0xdd,
	0x5f, 0x70, 0xbd, 0xf1, 0xee, 0xa5, 0xe6, 0xd0, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0xc2, 0x2d, 0xe9, 0x2b, 0x03, 0x00, 0x00,
}
