// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user_microservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateUser
type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreateUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetUserByEmail
type GetUserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailRequest) Reset()         { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()    {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *GetUserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailRequest.Unmarshal(m, b)
}
func (m *GetUserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailRequest.Merge(m, src)
}
func (m *GetUserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailRequest.Size(m)
}
func (m *GetUserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailRequest proto.InternalMessageInfo

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserByEmailResponse struct {
	Message              string                      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *GetUserByEmailResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUserByEmailResponse) Reset()         { *m = GetUserByEmailResponse{} }
func (m *GetUserByEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponse) ProtoMessage()    {}
func (*GetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *GetUserByEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponse.Unmarshal(m, b)
}
func (m *GetUserByEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponse.Merge(m, src)
}
func (m *GetUserByEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponse.Size(m)
}
func (m *GetUserByEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponse proto.InternalMessageInfo

func (m *GetUserByEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserByEmailResponse) GetData() *GetUserByEmailResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserByEmailResponseData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByEmailResponseData) Reset()         { *m = GetUserByEmailResponseData{} }
func (m *GetUserByEmailResponseData) String() string { return proto.CompactTextString(m) }
func (*GetUserByEmailResponseData) ProtoMessage()    {}
func (*GetUserByEmailResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *GetUserByEmailResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByEmailResponseData.Unmarshal(m, b)
}
func (m *GetUserByEmailResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByEmailResponseData.Marshal(b, m, deterministic)
}
func (m *GetUserByEmailResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByEmailResponseData.Merge(m, src)
}
func (m *GetUserByEmailResponseData) XXX_Size() int {
	return xxx_messageInfo_GetUserByEmailResponseData.Size(m)
}
func (m *GetUserByEmailResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByEmailResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByEmailResponseData proto.InternalMessageInfo

func (m *GetUserByEmailResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserByEmailResponseData) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// GetUserByEmail
type GetListUserByRoleRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserByRoleRequest) Reset()         { *m = GetListUserByRoleRequest{} }
func (m *GetListUserByRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetListUserByRoleRequest) ProtoMessage()    {}
func (*GetListUserByRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *GetListUserByRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserByRoleRequest.Unmarshal(m, b)
}
func (m *GetListUserByRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserByRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetListUserByRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserByRoleRequest.Merge(m, src)
}
func (m *GetListUserByRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetListUserByRoleRequest.Size(m)
}
func (m *GetListUserByRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserByRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserByRoleRequest proto.InternalMessageInfo

func (m *GetListUserByRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type GetListUserByRoleResponse struct {
	Message              string                           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*GetListUserByRoleResponseData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetListUserByRoleResponse) Reset()         { *m = GetListUserByRoleResponse{} }
func (m *GetListUserByRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetListUserByRoleResponse) ProtoMessage()    {}
func (*GetListUserByRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *GetListUserByRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserByRoleResponse.Unmarshal(m, b)
}
func (m *GetListUserByRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserByRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetListUserByRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserByRoleResponse.Merge(m, src)
}
func (m *GetListUserByRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetListUserByRoleResponse.Size(m)
}
func (m *GetListUserByRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserByRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserByRoleResponse proto.InternalMessageInfo

func (m *GetListUserByRoleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetListUserByRoleResponse) GetData() []*GetListUserByRoleResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetListUserByRoleResponseData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserByRoleResponseData) Reset()         { *m = GetListUserByRoleResponseData{} }
func (m *GetListUserByRoleResponseData) String() string { return proto.CompactTextString(m) }
func (*GetListUserByRoleResponseData) ProtoMessage()    {}
func (*GetListUserByRoleResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *GetListUserByRoleResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserByRoleResponseData.Unmarshal(m, b)
}
func (m *GetListUserByRoleResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserByRoleResponseData.Marshal(b, m, deterministic)
}
func (m *GetListUserByRoleResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserByRoleResponseData.Merge(m, src)
}
func (m *GetListUserByRoleResponseData) XXX_Size() int {
	return xxx_messageInfo_GetListUserByRoleResponseData.Size(m)
}
func (m *GetListUserByRoleResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserByRoleResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserByRoleResponseData proto.InternalMessageInfo

func (m *GetListUserByRoleResponseData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetListUserByRoleResponseData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetListUserByRoleResponseData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetListUserByRoleResponseData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetListUserByRoleResponseData) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetListUserByRoleResponseData) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user_microservice.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user_microservice.CreateUserResponse")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "user_microservice.GetUserByEmailRequest")
	proto.RegisterType((*GetUserByEmailResponse)(nil), "user_microservice.GetUserByEmailResponse")
	proto.RegisterType((*GetUserByEmailResponseData)(nil), "user_microservice.GetUserByEmailResponseData")
	proto.RegisterType((*GetListUserByRoleRequest)(nil), "user_microservice.GetListUserByRoleRequest")
	proto.RegisterType((*GetListUserByRoleResponse)(nil), "user_microservice.GetListUserByRoleResponse")
	proto.RegisterType((*GetListUserByRoleResponseData)(nil), "user_microservice.GetListUserByRoleResponseData")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xc7, 0x91, 0x2c, 0xdb, 0xf5, 0x18, 0x0c, 0x5e, 0xea, 0xb2, 0x15, 0x18, 0x8a, 0x68, 0xc1,
	0xa5, 0xb5, 0x5c, 0xdc, 0x63, 0x4e, 0x76, 0x1c, 0x7c, 0xc9, 0x49, 0x21, 0x87, 0xe4, 0x62, 0x36,
	0xd6, 0x10, 0x04, 0x96, 0xa5, 0xec, 0xae, 0x12, 0x42, 0x1e, 0x29, 0x0f, 0x91, 0x4b, 0x1e, 0x2c,
	0x68, 0xf5, 0x61, 0xc5, 0x92, 0x3f, 0x42, 0x2e, 0x62, 0x67, 0x67, 0x76, 0xfe, 0xb3, 0xbf, 0x99,
	0x15, 0xf4, 0x42, 0x1e, 0xc8, 0x60, 0x14, 0x09, 0xe4, 0xea, 0x63, 0x2b, 0x9b, 0x74, 0xe3, 0xf5,
	0xc2, 0xf7, 0x96, 0x3c, 0x10, 0xc8, 0xef, 0xbd, 0x25, 0x5a, 0x3e, 0x74, 0x4f, 0x39, 0x32, 0x89,
	0x97, 0x02, 0xb9, 0x83, 0x77, 0x11, 0x0a, 0x49, 0x08, 0x18, 0x6b, 0xe6, 0x23, 0xd5, 0x7e, 0x68,
	0x83, 0x96, 0xa3, 0xd6, 0xe4, 0x2b, 0xd4, 0xd1, 0x67, 0xde, 0x8a, 0xea, 0x6a, 0x33, 0x31, 0x88,
	0x09, 0x5f, 0x42, 0x26, 0xc4, 0x43, 0xc0, 0x5d, 0x5a, 0x53, 0x8e, 0xdc, 0x8e, 0xb3, 0xf0, 0x60,
	0x85, 0xd4, 0x48, 0xb2, 0xc4, 0x6b, 0xcb, 0x06, 0x52, 0x94, 0x13, 0x61, 0xb0, 0x16, 0x48, 0x28,
	0x34, 0x7d, 0x14, 0x82, 0xdd, 0x66, 0x92, 0x99, 0x69, 0x0d, 0xa1, 0x37, 0x47, 0x19, 0x07, 0x4f,
	0x1f, 0xcf, 0x62, 0xc5, 0xac, 0xc4, 0xbc, 0x1c, 0xad, 0x50, 0x8e, 0x15, 0xc1, 0xb7, 0xed, 0xf0,
	0x43, 0x12, 0x64, 0x02, 0x86, 0xcb, 0x24, 0x53, 0xf7, 0x6a, 0x8f, 0x87, 0x76, 0x89, 0x91, 0x5d,
	0x9d, 0x72, 0xc6, 0x24, 0x73, 0xd4, 0x51, 0xeb, 0x55, 0x03, 0x73, 0x77, 0x10, 0xe9, 0x80, 0xee,
	0xb9, 0xa9, 0xac, 0xee, 0xb9, 0x39, 0x5e, 0xbd, 0x0a, 0x6f, 0x6d, 0x17, 0x5e, 0x63, 0x07, 0xde,
	0xfa, 0x06, 0x2f, 0xe9, 0x03, 0x2c, 0x15, 0x5e, 0x77, 0xc1, 0x24, 0x6d, 0x28, 0x4f, 0x2b, 0xdd,
	0x99, 0xc8, 0xd8, 0x1d, 0x85, 0x6e, 0xe6, 0x6e, 0x26, 0xee, 0x74, 0x67, 0x22, 0x2d, 0x1b, 0xe8,
	0x1c, 0xe5, 0xb9, 0x27, 0xd2, 0x9b, 0x38, 0xc1, 0x0a, 0x0b, 0x23, 0xa1, 0xd4, 0xb4, 0x42, 0x33,
	0x9f, 0xe0, 0x7b, 0x45, 0xfc, 0x41, 0xe0, 0xb3, 0x1c, 0x78, 0x6d, 0xd0, 0x1e, 0xff, 0xab, 0x06,
	0x5e, 0x9d, 0xb5, 0xc0, 0xfc, 0x59, 0x83, 0xfe, 0xde, 0xb8, 0x4f, 0x60, 0xaf, 0x98, 0xdc, 0x2d,
	0xb4, 0xf5, 0xfd, 0x68, 0x1b, 0x5b, 0x68, 0xc7, 0x2f, 0x3a, 0xb4, 0xe3, 0x32, 0x2f, 0x92, 0x1b,
	0x92, 0x2b, 0x80, 0xcd, 0x3b, 0x20, 0x3f, 0x2b, 0x18, 0x94, 0x5e, 0xa5, 0xf9, 0xeb, 0x40, 0x54,
	0x0a, 0x1e, 0xa1, 0xf3, 0x7e, 0x16, 0xc9, 0xe0, 0x88, 0x99, 0x4e, 0x24, 0x7e, 0x1f, 0x3d, 0xfd,
	0x64, 0x0d, 0xdd, 0x12, 0x7e, 0xf2, 0xe7, 0xb8, 0x66, 0x26, 0x62, 0x7f, 0x3f, 0xd2, 0xf9, 0xa9,
	0x79, 0x4d, 0x47, 0xea, 0x2f, 0x76, 0x52, 0x3a, 0x75, 0xd3, 0x50, 0x8e, 0xff, 0x6f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x08, 0x83, 0xb8, 0xf7, 0x04, 0x00, 0x00,
}
